- name: "Create DNS Records"
  hosts: support
  become: True
  become_method: sudo
  become_user: root
  vars_files:
    - ./roles/default_vars/vars/main.yml
  roles:
    - role: create_dns_server

- name: "Create DHCP Server"
  hosts: support
  become: True
  become_method: sudo
  become_user: root
  vars_files:
    - ./roles/default_vars/vars/secrets.yml
    - ./roles/default_vars/vars/main.yml
  roles:
    - role: create_dhcp_server

- name: "Create PXE Server"
  hosts: support
  become: True
  become_method: sudo
  become_user: root
  vars_files:
    - ./roles/default_vars/vars/secrets.yml
    - ./roles/default_vars/vars/main.yml
  roles:
    - role: create_pxe_server
    
- name: "Install and Start Apache"
  hosts: support
  become: True
  become_method: sudo
  become_user: root
  vars_files:
    - ./roles/default_vars/vars/secrets.yml
    - ./roles/default_vars/vars/main.yml
  roles:
    - role: create_http_server

- name: "Create HAPROXY Server"
  hosts: support
  become: True
  become_method: sudo
  become_user: root
  vars_files:
    - ./roles/default_vars/vars/secrets.yml
    - ./roles/default_vars/vars/main.yml
  roles:
    - role: create_haproxy_server

- name: "Pull OC Client and COREOS Files"
  hosts: support
  become: True
  become_method: sudo
  become_user: root
  vars_files:
    - ./roles/default_vars/vars/secrets.yml
    - ./roles/default_vars/vars/main.yml
  roles:
    - role: pull_oc_images

- name: "Deploy Registry"
  hosts: support
  become: True
  become_method: sudo
  become_user: root
  vars_files:
    - ./roles/default_vars/vars/main.yml
    - ./roles/default_vars/vars/secrets.yml
  roles:
    - role: deploy_registry

- name: "Mirror Registry"
  hosts: support
  become: True
  become_method: sudo
  become_user: root
  vars_files:
    - ./roles/default_vars/vars/main.yml
    - ./roles/default_vars/vars/secrets.yml
  roles:
    - role: mirror_registry

- name: "Create Install Config"
  hosts: support
  become: True
  become_method: sudo
  become_user: root
  vars_files:
    - ./roles/default_vars/vars/secrets.yml
    - ./roles/default_vars/vars/main.yml
  roles:
    - role: create_install_config
