---
# tasks file for pull_coreos_images

- name: Download Installer Live InitRamFS
  get_url:
    url: "{{ rhcos_mirror }}/{{ installer_initramfs_live_file }}"
    dest: "/var/lib/tftpboot/pxelinux/{{ installer_initramfs_live_file }}"

- name: Download Installer Live Kernel File
  get_url:
    url: "{{ rhcos_mirror }}/{{ installer_kernel_live_file }}"
    dest: "/var/lib/tftpboot/pxelinux/{{ installer_kernel_live_file }}"

- name: Download Live RootFS File
  get_url:
    url: "{{ rhcos_mirror }}/{{ installer_liverootfs_file }}"
    dest: "/var/www/html/{{ installer_liverootfs_file }}"

- name: Download OC Linux Client
  get_url:
    url: "{{ oc_files_url }}/{{ oc_client_url }}"
    dest: "{{ artifact_dir }}/{{ oc_client_url }}"

- name: Download OC Linux Installer
  get_url:
    url: "{{ oc_files_url }}/{{ oc_install_file }}"
    dest: "{{ artifact_dir }}/{{ oc_install_file }}"

- name: Copy oc client to path
  shell:
    cmd: tar -C /usr/local/bin -xvzpf "{{ artifact_dir }}/{{ oc_client_url }}" oc
